# Generated by Django 4.2.2 on 2023-06-16 00:45

import django.core.validators
from django.db import migrations, models
import publication.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('permalink', models.CharField(blank=True, max_length=255, null=True)),
                ('media', models.FileField(upload_to='publications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), publication.util.validate_file_size_limit_5mb])),
            ],
        ),
    ]
